spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HRmanagement?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HR-MANAGEMENT
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090